const authService = require('../services/authService');
const { AppError } = require('../middleware/errorHandler');

exports.register = async (req, res, next) => {
  try {
    const userData = {
      email: req.body.email,
      password: req.body.password,
      first_name: req.body.first_name,
      last_name: req.body.last_name,
      phone: req.body.phone,
      street: req.body.street,
      house_number: req.body.house_number,
      city: req.body.city,
      postal_code: req.body.postal_code,
      tax_id: req.body.tax_id
    };

    const organizationData = req.body.organization || null;

    const result = await authService.register(userData, organizationData);

    res.status(201).json({
      status: 'success',
      data: {
        user: result.user,
        organization: result.organization,
        token: result.token
      }
    });
  } catch (error) {
    next(error);
  }
};

exports.login = async (req, res, next) => {
  try {
    console.log('DEBUG: Rozpoczęcie logowania');
    console.log('DEBUG: Dane logowania:', { 
      email: req.body.email, 
      hasPassword: !!req.body.password 
    });

    const { email, password } = req.body;

    try {
      console.log('DEBUG: Wywołanie authService.login');
      const result = await authService.login(email, password);
      console.log('DEBUG: Otrzymano wynik z authService.login');
      
      // Zaloguj odpowiedź bez wrażliwych danych
      console.log('DEBUG: Sukces logowania, zwracam użytkownika i token');
      
      res.status(200).json({
        status: 'success',
        data: {
          user: result.user,
          organizations: result.organizations,
          token: result.token
        }
      });
    } catch (serviceError) {
      console.log('DEBUG: Błąd z authService:', serviceError.message);
      throw serviceError;
    }
  } catch (error) {
    console.log('DEBUG: Końcowy błąd w kontrolerze:', error.message);
    next(new AppError('Nieprawidłowe dane logowania', 401));
  }
};

exports.getMe = async (req, res, next) => {
  try {
    const result = await authService.getUserProfile(req.userId);

    res.status(200).json({
      status: 'success',
      data: {
        user: result.user,
        organizations: result.organizations
      }
    });
  } catch (error) {
    console.log("DEBUG CRITICAL: Błąd logowania:", error);
    next(new AppError("Nieprawidłowe dane logowania", 401));
  }
};
